//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServidorCertificacao.AutorizacaoSVRS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", ConfigurationName="AutorizacaoSVRS.NFeAutorizacao4Soap")]
    public interface NFeAutorizacao4Soap {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeAutorizacaoLote não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse nfeAutorizacaoLote(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação nfeAutorizacaoLoteZip não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse nfeAutorizacaoLoteZip(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeAutorizacaoLoteRequest() {
        }
        
        public nfeAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteResponse() {
        }
        
        public nfeAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public string nfeDadosMsgZip;
        
        public nfeAutorizacaoLoteZipRequest() {
        }
        
        public nfeAutorizacaoLoteZipRequest(string nfeDadosMsgZip) {
            this.nfeDadosMsgZip = nfeDadosMsgZip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteZipResponse() {
        }
        
        public nfeAutorizacaoLoteZipResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeAutorizacao4SoapChannel : ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeAutorizacao4SoapClient : System.ServiceModel.ClientBase<ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap>, ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap {
        
        public NFeAutorizacao4SoapClient() {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap.nfeAutorizacaoLote(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest inValue = new ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse retVal = ((ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse> ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap.nfeAutorizacaoLoteAsync(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest inValue = new ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap.nfeAutorizacaoLoteZip(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZip(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLoteZip(string nfeDadosMsgZip) {
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest inValue = new ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse retVal = ((ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteZip(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse> ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap.nfeAutorizacaoLoteZipAsync(ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(string nfeDadosMsgZip) {
            ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest inValue = new ServidorCertificacao.AutorizacaoSVRS.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            return ((ServidorCertificacao.AutorizacaoSVRS.NFeAutorizacao4Soap)(this)).nfeAutorizacaoLoteZipAsync(inValue);
        }
    }
}
